function f = state_transition(dt,u1,u2,u3,u4,u5,u6,x1,x2,x3,x4,x5,x6,x7,x8,x9)
%STATE_TRANSITION
%    F = STATE_TRANSITION(DT,U1,U2,U3,U4,U5,U6,X1,X2,X3,X4,X5,X6,X7,X8,X9)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    24-Jul-2013 16:50:51

t2 = pi.*x9.*(1.0./1.8e2);
t3 = pi.*x7.*(1.0./1.8e2);
t4 = sin(t3);
t5 = sin(t2);
t6 = cos(t3);
t7 = cos(t2);
t8 = pi.*x8.*(1.0./1.8e2);
t9 = sin(t8);
t10 = cos(t8);
t11 = tan(t8);
f = [x1+dt.*x4,x2+dt.*x5,x3+dt.*x6,x4+dt.*(-u5.*(t5.*t6-t4.*t7.*t9)+u6.*(t4.*t5+t6.*t7.*t9)+t7.*t10.*u4),x5+dt.*(u5.*(t6.*t7+t4.*t5.*t9)-u6.*(t4.*t7-t5.*t6.*t9)+t5.*t10.*u4),x6-dt.*(t9.*u4-t4.*t10.*u5-t6.*t10.*u6+5.520653160719109e15./5.62949953421312e14),x7+dt.*(u1+t4.*t11.*u2+t6.*t11.*u3),x8-dt.*(t4.*u3-t6.*u2),x9+(dt.*(t4.*u2+t6.*u3))./t10];
